import 'package:flutter/material.dart';
import '../utils/selection_decoration.dart';

/// Shows a numbered-grid picker dialog (used for chapter and verse
/// selection) and returns once the user picks an item or cancels.
///
/// [itemCount] cells are generated by index; [labelForIndex] supplies each
/// cell's display text (defaults to `index + 1`, used for chapters), and
/// [isSelectedIndex]/[onSelectedIndex] operate on the 0-based index so
/// callers can select by index even when the display label isn't
/// contiguous (e.g. verse numbers).
Future<void> showGridSelectorDialog(
  BuildContext context, {
  required String title,
  required int itemCount,
  required bool Function(int index) isSelectedIndex,
  required ValueChanged<int> onSelectedIndex,
  String Function(int index)? labelForIndex,
}) {
  return showDialog<void>(
    context: context,
    builder: (dialogContext) {
      return AlertDialog(
        title: Text(title),
        content: SizedBox(
          width: double.maxFinite,
          child: GridView.builder(
            shrinkWrap: true,
            gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
              crossAxisCount: 4,
              crossAxisSpacing: 8,
              mainAxisSpacing: 8,
              childAspectRatio: 1.4,
            ),
            itemCount: itemCount,
            itemBuilder: (context, index) {
              final selected = isSelectedIndex(index);
              final label = labelForIndex?.call(index) ?? '${index + 1}';
              return InkWell(
                onTap: () {
                  Navigator.pop(dialogContext);
                  onSelectedIndex(index);
                },
                child: Container(
                  decoration: BoxDecoration(
                    color: selected
                        ? Theme.of(context).colorScheme.primaryContainer
                        : Theme.of(context).colorScheme.surfaceContainerHighest,
                    borderRadius: BorderRadius.circular(8),
                    border: selectionBorder(
                      context,
                      isSelected: selected,
                      selectedWidth: 2,
                      unselectedColor: Colors.transparent,
                      unselectedWidth: 2,
                    ),
                  ),
                  alignment: Alignment.center,
                  child: Text(
                    label,
                    style: TextStyle(
                      fontWeight: selected ? FontWeight.bold : FontWeight.normal,
                      color: selected
                          ? Theme.of(context).colorScheme.onPrimaryContainer
                          : null,
                    ),
                  ),
                ),
              );
            },
          ),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(dialogContext),
            child: const Text('Cancel'),
          ),
        ],
      );
    },
  );
}
